# Generated by Django 5.1.3 on 2024-11-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_service_icon_service_icon_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
