# Generated by Django 5.1.3 on 2024-11-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_service_icon_class_service_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='icon',
            new_name='image',
        ),
    ]
