# Generated by Django 5.1.3 on 2024-11-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_icon_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
