name: Deploy on VPS

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: self-hosted  # Ensure this uses a self-hosted runner configured on your VPS

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build and run the Docker container
      - name: Build and Run Docker Container
        run: |
        
          cd /home/cb/projects/ojassolutions.com.np || exit 1
        
          docker build -t ojassolutions .
          
          docker stop ojassolutions.com.np || true
          docker rm ojassolutions.com.np || true          
         
          docker run -d --name ojassolutions.com.np -p 8001:8001 ojassolutions
