name: Deploy on VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: Connect to VPS and deploy
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22

          script: |
            
            cd /home/cb/projects/ojassolutions.com.np || exit 1
            
            git pull origin main || exit 1
            
            docker build -t ojassolutions .
            
            docker stop ojassolutions.com.np || true
            docker rm ojassolutions.com.np || true
            
            docker run -d --name ojassolutions.com.np -p 8001:80 ojassolutions
